name: Quality

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  prettier:
    name: Prettier
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Run Prettier
        run: turbo format --continue

  eslint:
    name: ESLint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup and install
        uses: ./tooling/github-actions/install

      - name: Lint
        run: turbo lint --continue

  typecheck:
    name: TypeCheck
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Cache TypeScript TSBuild Info Files
        id: cache-typescript-tsbuildinfo
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/*-tsbuildinfo.json
          # We use the commit hash as the key to always update the cache as a
          # workaround to this issue:
          # https://github.com/actions/cache/issues/106
          key: ${{ runner.os }}-cache-typescript-tsbuildinfo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-typescript-tsbuildinfo-

      - name: Run TypeScript type check
        run: turbo typecheck --continue

  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --with-deps

      - name: Setup database
        run: |
          cp .env.example .env
          docker compose up -d --wait
          pnpm db:push
          pnpm db:seed

      - name: Build
        run: turbo build
        env:
          GITHUB_ID: ' '
          GITHUB_SECRET: ' '

      - name: Run Playwright tests
        run: turbo test:e2e --continue
        env:
          DATABASE_URL: mysql://dev:dev@localhost/typehero
          GITHUB_ID: ' '
          GITHUB_SECRET: ' '
          NEXTAUTH_SECRET: 'kGvjABB9ZZsxhYFyxMT4ApohaIvfuNSRMIthI+usjA0='
          NEXTAUTH_URL: http://localhost:3000

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: apps/web/playwright-report/

      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > prNumber

      - name: Upload prNumber
        uses: actions/upload-artifact@v3
        with:
          name: prNumber
          path: prNumber
